[package]
name = "rustd5"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
codespan-reporting = "0.11.1"
derive_more = "0.99.17"
glob = "0.3.0"
itertools = "0.10.3"
peg = "0.8.0"
rustyline = "9.1.2"
test-generator = "0.3.0"
